version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/backend

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 300

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
