version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /var/www/html/backend

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
      timeout: 300

  ApplicationStart:
    - location: scripts/start_pm2.sh
      runas: ubuntu
      timeout: 300

  ValidateService:
    - location: scripts/validate.sh
      runas: ubuntu
      timeout: 60
  permissions:
  - object: /var/www/html/backend
    owner: ubuntu
    group: ubuntu
    type:
      - file
      - directory
    mode: 755
