version: 0.2

phases:
  install:
    commands:
      - echo "No build step for backend"

  build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - server.js
    - package.json
    - package-lock.json
  discard-paths: no
