version: 0.2

phases:
  install:
    commands:
      - echo "Install not required in build"
  build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - server.js
    - package.json
    - package-lock.json
